// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcdm_fs_h)
#define octave_mx_fcdm_fs_h 1
#include "fCMatrix.h"
#include "fCDiagMatrix.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexDiagMatrix, float, OCTAVE_API)
#endif
