// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcdm_fcs_h)
#define octave_mx_fcdm_fcs_h 1
#include "fCMatrix.h"
#include "fCDiagMatrix.h"
#include "oct-cmplx.h"
#include "mx-op-decl.h"
DMS_BIN_OP_DECLS (FloatComplexMatrix, FloatComplexDiagMatrix, FloatComplex, OCTAVE_API)
#endif
