// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcs_fcdm_h)
#define octave_mx_fcs_fcdm_h 1
#include "fCMatrix.h"
#include "oct-cmplx.h"
#include "fCDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplex, FloatComplexDiagMatrix, OCTAVE_API)
#endif
