// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fs_fdm_h)
#define octave_mx_fs_fdm_h 1
#include "fMatrix.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (FloatMatrix, float, FloatDiagMatrix, OCTAVE_API)
#endif
