// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_fcs_fdm_h)
#define octave_mx_fcs_fdm_h 1
#include "fCMatrix.h"
#include "oct-cmplx.h"
#include "fDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (FloatComplexMatrix, FloatComplex, FloatDiagMatrix, OCTAVE_API)
#endif
