// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_s_cdm_h)
#define octave_mx_s_cdm_h 1
#include "CMatrix.h"
#include "CDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (ComplexMatrix, double, ComplexDiagMatrix, OCTAVE_API)
#endif
