// DO NOT EDIT -- generated by mk-ops
#if !defined (octave_mx_s_dm_h)
#define octave_mx_s_dm_h 1
#include "dMatrix.h"
#include "dDiagMatrix.h"
#include "mx-op-decl.h"
SDM_BIN_OP_DECLS (Matrix, double, DiagMatrix, OCTAVE_API)
#endif
